export const PRODUCT_LISTS_REQUEST="PRODUCT_LISTS_REQUEST"
export const PRODUCT_LISTS_SUCCESS="PRODUCT_LISTS_SUCCESS"
export const PRODUCT_LISTS_FAILURE = "PRODUCT_LISTS_FAILURE"


export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAILURE="PRODUCT_DETAILS_FAILURE"